author_me: jonashendrickx
title: Jonas Hendrickx
tagline: 'Software Engineer'
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jon-hen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonashendrickx
github_username:  jonashendrickx
paginate: 10
paginate_path: /page/:num
permalink: /:slug

# About/contact
author:
  name: Jonas Hendrickx
  url: https://twitter.com/jonashendrickx
  email: jonashendrickx@outlook.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version: 1.1.0
google_analytics_id: # UA-XXXX-Y
google_adsense_id: ca-pub-4101620276407169

collections:
  authors:
    output: true
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:slug
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
