title: Jonas Hendrickx
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Jonas Hendrickx
avatar: assets/img/authors/jonashendrickx.jpg
email: hendrickx.jonas.pvt@gmail.com

skin: midnight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jonashendrickx.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: jonashendrickx
  card: summary
logo: assets/img/authors/jonashendrickx.jpg
social:
  name: Jonas Hendrickx
  links:
    - https://twitter.com/jonashendrickx
    - https://github.com/jonashendrickx
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:slug
  - scope:
      path: ""
    values:
      layout: "default"